### ISSUE TITLE
 DeadboltActions not working

### ISSUE THREAD

**Issue by raziboy939** [schaloner/deadbolt-2-scala#49]
Hi, Im running into an issue with DeadboltActions.  I think it has to do with dependency injection?

Im running Scala 2.11.12 and Deadbolt 2.6.0 with Play 2.7.

Unexpected exception
ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.AbstractMethodError: Receiver class be.objectify.deadbolt.scala.DeadboltActions does not define or inherit an implementation of the resolved method abstract play$api$mvc$Results$_setter_$PreconditionRequired_$eq(Lplay/api/mvc/Results$Status;)V of interface play.api.mvc.Results.
  at be.objectify.deadbolt.scala.DeadboltActions.<init>(DeadboltActions.scala:34)
  at be.objectify.deadbolt.scala.DeadboltModule.bindings(DeadboltModule.scala:30):
Binding(class be.objectify.deadbolt.scala.DeadboltActions to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating be.objectify.deadbolt.scala.DeadboltActions
    for the 3rd parameter of controllers.HomeController.<init>(HomeController.scala:17)
  while locating controllers.HomeController
    for the 2nd parameter of router.Routes.<init>(Routes.scala:29)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for the 3rd parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:305)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:253)
  at play.api.DefaultApplication.class(Application.scala:252)
  while locating play.api.DefaultApplication
  while locating play.api.Application
1 error

**Comment by ptagr** [comment]
@raziboy939 were you able to find a workaround for this? facing the same issue with play `2.7.2` and deadbolt `2.6.1`

**Comment by hinterwaldlerFlo** [comment]
> @raziboy939 were you able to find a workaround for this? facing the same issue with play `2.7.2` and deadbolt `2.6.1`

did you find a solution?
